version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sectoral-hub-prod
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: sectoral-db-prod
    restart:  unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - production-network
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: sectoral-nginx-prod
    restart: unless-stopped
    ports:
      - "8080:80"
    # In production, the application code should be part of the image.
    # We only mount the Nginx configuration.
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - production-network
    depends_on:
      - app

networks:
  production-network:
    driver: bridge

volumes:
  db_data: